---
baseurl: "https://lannyMa.github.io/"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-cn"
title: "æ¯›å°"
theme: "beautifulhugo"
metaDataFormat: "yaml"
subtitle: "æ²¡æ—¶é—´äº†,ä¸Šè½¦å§..."
dateFormat: "January 2, 2006"
description: "python ğŸ¤˜ Go"
algolia:
  index: "maotai-blog"
  key: "454a6219083be3c1c09c6f825df6a7e9"
  appID: "FA18DC53LC"
---
